steps:
- name: 'gcr.io/cloud-builders/git'
  entrypoint: /bin/bash
  args:
    - -c
    - |
        git clone --branch $BRANCH_NAME https://github.com/guillaumeblaquiere/cloudbuildtest.git /tmp/repo ;
        mv /tmp/repo/.git .
        ls -la
        git diff --name-only --diff-filter=AMDR @~..@ | grep "/" | cut -d"/" -f1 | uniq > /workspace/diff
        cat /workspace/diff
- name: 'python:3.7'
  entrypoint: /bin/bash
  args: 
    - -c
    - |
       for i in $$(cat /workspace/diff); do 
       echo $$i
       done
