steps:
- name: 'gcr.io/cloud-builders/git'
  entrypoint: /bin/bash
  args:
    - -c
    - |
      git version > /workspace/files.txt
- name: 'gcr.io/cloud-builders/git'
  entrypoint: /bin/bash
  args: 
    - -c
    - |
      echo "File contents " $(cat /workspace/files.txt)
